version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16

jobs:
  build-and-test:
    executor: node-executor
    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: npm install

      # Start the Node.js server in the background
      - run:
          name: Start Node Server
          command: node ./app.js
          background: true

      # Wait for the server to start
      - run:
          name: Wait for Server
          command: sleep 5

      # Run Cypress tests
      - run:
          name: Run Cypress Tests
          command: npx cypress run

      # Save the diff image if it exists
      - run:
          name: Save Diff Image
          command: |
            if [ -f cypress/snapshots/__diff_output__/home-page-snapshot.png ]; then
              mv cypress/snapshots/__diff_output__/home-page-snapshot.png cypress/snapshots/home-page-snapshot-diff.png
            fi

      # Ask user to update benchmarked image if diff exists
      - run:
          name: Update Benchmark Image
          command: |
            if [ -f cypress/snapshots/home-page-snapshot-diff.png ]; then
              read -p "Do you want to update the benchmarked image? (y/n) " choice
              if [[ $choice =~ ^[Yy]$ ]]; then
                mv cypress/snapshots/home-page-snapshot.png cypress/snapshots/home-page-snapshot.png.bak
                mv cypress/snapshots/home-page-snapshot-diff.png cypress/snapshots/home-page-snapshot.png
              fi
            fi

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
