version: 2.1
jobs:
  build:
    environment:
      EXIT_CODE: 0
      UPDATE: 0
    docker:
      - image: cimg/node:16.20-browsers
    working_directory: ~/cypress-circleci-snapshot
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "9f:fb:61:53:40:9c:18:a1:ce:38:b8:00:7b:d6:14:8e"
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Start Node Server
          command: node app.js
          background: true
      - run:
          name: wait for localhost
          shell: /bin/sh
          command: wget --waitretry=3 --tries=40 --timeout=5 --retry-connrefused --spider --quiet http://localhost:3000
      - run: 
          name: Cypress Tests
          command: |
            set +e
            if [[ "$UPDATE" -eq 1 ]]; then
              # Run tests and update the snapshots
              npm run cyupdate:run
            else
              # Run without updating the snapshot
              npm run cy:run
            fi
            # Check the exit status of tests
            CURR_STATUS=$?
            if [[ $CURR_STATUS -ne 0 ]]; then
              echo "EXIT_CODE=1" >> $BASH_ENV
            fi
            set -e

      - store_artifacts:
          path: ~/cypress-circleci-snapshot/cypress-visual-screenshots/baseline
          destination: cypress-visual-screenshots/baseline
      - store_artifacts:
          path: ~/cypress-circleci-snapshot/cypress-visual-screenshots/comparision
          destination: cypress-visual-screenshots/comparision
      - store_artifacts:
            path: ~/cypress-circleci-snapshot/cypress-visual-screenshots/diff
            destination: cypress-visual-screenshots/diff
      # - run:
      #     name: Commit and push code
      #     command: |
      #       # Push the snapshots to github
      #       git config user.email "rijumondal377@gmail.com"
      #       git config user.name "riju377"
      #       git add . || true
      #       git commit -m "CircleCI automatic commit" || true
      #       git push origin main || true
      # - run:
      #     name: Finally
      #     command: |
      #       # If any test fails we return error
      #       if [[ "$EXIT_CODE" -ne 0 ]]; then
      #         echo "Exit status of your-command-1"
      #         exit 1
      #       fi

workflows:
  master_workflow:
    jobs:
      - build



# curl -H "Circle-Token:CCIPAT_LRuf2amSDCgMAqYtMjawZ1_bd12c8ed789f8138451d78ed2001463306c82c3b" https://circleci.com/api/v1.1/project/github/riju377/cypress-circleci-snapshot/88/artifacts \ | grep -o 'https://[^"]*' \ | wget --verbose --header "Circle-Token:CCIPAT_LRuf2amSDCgMAqYtMjawZ1_bd12c8ed789f8138451d78ed2001463306c82c3b" --input-file -


# curl -X GET https://circleci.com/api/v2/project/github/riju377/cypress-circleci-snapshot/93/artifacts \
#  --header "Content-Type: application/json" \
#  --header "Accept: application/json" \
#  --header "Circle-Token:CCIPAT_LRuf2amSDCgMAqYtMjawZ1_bd12c8ed789f8138451d78ed2001463306c82c3b" \
#  | grep -o 'https://[^"]*' \
#  | wget --header="Circle-Token:"CCIPAT_LRuf2amSDCgMAqYtMjawZ1_bd12c8ed789f8138451d78ed2001463306c82c3b"" -v -i -
