version: 2.1

orbs:
  cypress: cypress-io/cypress@3

jobs:
  build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: npm i

      # Start the Node server in the background
      - run:
          name: Start Node Server
          command: node app.js
          background: true

      # Wait for the Node server to be available
      - run:
          name: Wait for Server
          command: |
            until nc -z localhost 3000; do
              sleep 1
            done

      # Run Cypress tests
      - cypress/run:
          cypress-command: npx cypress run --browser chrome
          install-browsers: true
          # start-command: npm run start:dev
