version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.20-browsers
    working_directory: ~/cypress-circleci-snapshot
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Start Node Server
          command: node app.js
          background: true
      - run:
          name: wait for localhost
          shell: /bin/sh
          command: wget --waitretry=3 --tries=40 --timeout=5 --retry-connrefused --spider --quiet http://localhost:3000
      - run: npm run cy:run

workflows:
  master_workflow:
    jobs:
      - build
