version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.20-browsers
    working_directory: ~/cypress-circleci-snapshot
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "9f:fb:61:53:40:9c:18:a1:ce:38:b8:00:7b:d6:14:8e"
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Start Node Server
          command: node app.js
          background: true
      - run:
          name: wait for localhost
          shell: /bin/sh
          command: wget --waitretry=3 --tries=40 --timeout=5 --retry-connrefused --spider --quiet http://localhost:3000
      - run: npm run cyr:run || true
      - run:
          name: Commit and push code
          command: |
            git config user.email "rijumondal377@gmail.com"
            git config user.name "riju377"
            git add .
            git commit -m "CircleCI automatic commit"
            git push origin main
      - run: |
          if [ -d diff_folder ]; then
            read -p "Do you want to run the command? (y/n) " choice
            if [ "$choice" == "y" ]; then
              # Run the command you want here
        - run: npx cypress run --env updateSnapshots=true || true
              echo "Running the command..."
            else
              echo "Skipping the command..."
            fi
          else
            echo "Diff folder not present. Skipping the command..."
          fi

workflows:
  master_workflow:
    jobs:
      - build
