version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.20-browsers
    working_directory: ~/cypress-circleci-snapshot
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "9f:fb:61:53:40:9c:18:a1:ce:38:b8:00:7b:d6:14:8e"
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Start Node Server
          command: node app.js
          background: true
      - run:
          name: wait for localhost
          shell: /bin/sh
          command: wget --waitretry=3 --tries=40 --timeout=5 --retry-connrefused --spider --quiet http://localhost:3000
      - run: 
          name: Cypress Tests
          command: |
            # percy and cypress exe
            echo 'export PERCY_TOKEN=$PERCY_TOKEN' >> $BASH_ENV
            npm run cy:percy

workflows:
  master_workflow:
    jobs:
      - build
